# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 476d76866ed1a935d5db68c22df16670d1ef83f7c7bd99a43f53c7cc84ff00ab56e4666690498bd937170a24150ad009e7cb6a71072bb0f9c31b80dd05c82eef

test:
  secret_key_base: 1dc3d0043e16300190d3c5a52519a5afacc7d36542658c28530feb8f8f3d913919fe6650c7f6578edc8b4a60ae95595a7d014326a31e569f27cd9ff6ac3cb9be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
